server:
  port: 8866
  servlet:
    context-path: /server
management:
  endpoints:
    web:
      cors:
        exposed-headers: "*"
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.107.177.14:3306/meatball?useUnicode=true&characterEncoding=utf-8&serverTimezone=Hongkong&useSSL=false
    username: root
    password: root123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  redis:
    host: 47.107.177.14
    port: 6397
    password: 123456
    database: 1
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 500